spark:
  target: local
  outputs:
    local:
      type: spark
      method: thrift
      host: 127.0.0.1
      port: 10000
      user: dbt
      schema: default
      connect_retries: 5
      connect_timeout: 10
      retry_all: true
      server_side_parameters:
        "spark.driver.memory": "4g"