spark:
  target: local
  location_root: s3a://result-parquet
  outputs:
    local:
      type: spark
      method: session
      host: localhost
      schema: default
      threads: 4
      server_side_parameters:
        "spark.driver.memory": "4g"
        "spark.executor.memory": "2g"
        "spark.hadoop.fs.s3a.access.key": "{{ env_var('AWS_ACCESS_KEY_ID') }}"
        "spark.hadoop.fs.s3a.secret.key": "{{ env_var('AWS_SECRET_KEY') }}"
        "spark.hadoop.fs.s3a.endpoint": "storage.yandexcloud.net"
        "spark.jars.packages": "org.apache.hudi:hudi-spark3-bundle_2.12:0.14.1,org.apache.hadoop:hadoop-aws:3.3.4"
        "spark.serializer": "org.apache.spark.serializer.KryoSerializer"
        "spark.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
        "spark.sql.legacy.allowNonEmptyLocationInCTAS": "true"
        "spark.sql.extensions": "org.apache.spark.sql.hudi.HoodieSparkSessionExtension"
        "spark.driver.userClassPathFirst": "true"