version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    healthcheck:
      test: ["CMD", "psql", "-U", "${POSTGRES_USER}", "${POSTGRES_DB}"]
    ports:
      - '5432:5432'

  minio:
    image: minio/minio:RELEASE.2023-06-29T05-12-28Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio-minio
    command: minio server --console-address ":9001" /data

  mc:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host rm local;
      /usr/bin/mc config host add --quiet --api s3v4 local http://minio:9000 minio minio-minio;
      /usr/bin/mc mb --quiet local/hudi/;
      "

  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      mc:
        condition: service_started
    env_file:
      - .env
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_DB=${POSTGRES_DB}
      - DATABASE_USER=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - S3_ENDPOINT_URL=${AWS_ENDPOINT}
      - S3_BUCKET=${S3_BUCKET}
      - S3_PREFIX=${S3_BUCKET}
    ports:
      - '9083:9083'
